### ISSUE TITLE
[Help] Start under zsh raises an error (using wayland on fedora 36)

### ISSUE THREAD

**Issue by webjoaoneto** [sonnyp/Commit#71] opened 2022-05-03 15:37 UTC
Hello.
Open Commit inside an bash terminar or even from Gnome menu is ok, but when i try to open from zsh shell (using ohmyzsh) Commit screen wont open:

```
➜  Docs flatpak run re.sonny.Commit

(re.sonny.Commit:2): Gtk-WARNING **: 12:36:35.606: cannot open display: 
➜  Docs
```
I've tried everything i now to make this open, but no success

(The same has happend when i tried to open from vscode terminal too)

**Comment by mpetuska** [comment] 2022-06-22 19:46
Seems to be related to #46

**Comment by sonnyp** [comment] 2022-08-08 19:49
It's not a bug in Commit, Feel free to discuss solutions or findings here but I'm closing since there is nothing I can do about this.

Looks to be https://github.com/flatpak/flatpak/issues/4690

You can try

```
flatpak run --env=GDK_BACKEND=wayland re.sonny.Commit
```

**Closed by sonnyp** 2022-08-08 19:49 UTC
