### ISSUE TITLE
Git flag 'verbose' makes app unusable

### ISSUE THREAD

**Issue by vilgotf** [sonnyp/Commit#10] opened 2021-05-08 18:40 UTC
`git commit --verbose` makes the commit button unclickable (old bug present in gnomit) on big diffs

![Screenshot from 2021-05-08 20-38-26](https://user-images.githubusercontent.com/26655508/117549926-6772c300-b03d-11eb-89ac-8cf5ea8c53f9.png)

**Comment by sonnyp** [comment] 2021-05-11 22:53
I cannot reproduce.

Please share more information.

How to reproduce? (repository, file to stage, ...)

git version?

Are you using the flatpak?

What is the value of `git config --global core.editor` ?

**Comment by sonnyp** [comment] 2021-05-11 23:04
Please reproduce the issue and before closing Commit share here the content of the file `.git/COMMIT_EDITMSG` from the repository in question.

**Comment by vilgotf** [comment] 2021-05-12 09:32
I used a VERY large commit message but I've been able to reproduced this on smaller commits.
[git-output.txt](https://github.com/sonnyp/Commit/files/6465132/git-output.txt)

**Comment by sonnyp** [comment] 2021-05-13 17:35
Turns out text was not escaped properly. Any commit - big or small with a `&` character fail. Fixed in #11

**Closed by sonnyp** 2021-05-13 17:35 UTC
